%% 

function [temperature_struct] = create_temperature_struct(valueHolder)

    field1 = 'ImageName';
    field2 = 'Strain';
    field3 = 'Temperature'; % percentage
    field4 = 'IPTG';
    
    field5 = 'TotalBoundaryPixels'; 
    field6 = 'NumberOfBoundariesMode'; 
    field7 = 'NumberOfVerticalBoundaryPixels'; 
    
    field8 = 'NumberOfColumnsConsidered'; 
    
    field9 = 'OverallMinDistance'; 
    field10 = 'OverallMaxDistance'; 
    field11 = 'OverallMeanDistance'; 
    field12 = 'MeanDistancesBtwnBoundaries'; % 1st element = inoculum width 
    field13 = 'MeanDistanceToInoc'; % boundary 1 = inoculum edge
    field14 = 'MeanDistanceInocToBound2'; 
    
    field15 = 'STDofDistancesBtwnBoundaries'; 
    field16 = 'MinSTDofDistances'; 
    field17 = 'MaxSTDofDistances'; 
    
    field18 = 'STDof2ndBoundaryLocations'; 
    field19 = 'STDofLastBoundaryLocations';
    field20 = 'MaxSTDofAllBoundaryLocations'; 

    temperature_struct = struct(field1,valueHolder,...
                  field2,valueHolder,...
                  field3,valueHolder,...
                  field4,valueHolder,...
                  field5,valueHolder,...
                  field6,valueHolder,...
                  field7,valueHolder,...
                  field8,valueHolder,...
                  field9,valueHolder,...
                  field10,valueHolder,...
                  field11,valueHolder,...
                  field12,valueHolder,...
                  field13,valueHolder,...
                  field14,valueHolder,...
                  field15,valueHolder,...
                  field16,valueHolder,...
                  field17,valueHolder,...
                  field18,valueHolder,...
                  field19,valueHolder,...
                  field20,valueHolder);
end